### ISSUE TITLE
Modulus deploy error

### ISSUE THREAD

**Issue by Lepozepo** [gadicc/meteor-phantomjs#1]
I can't seem to get it all working, I've installed spiderable and phantomjs locally and things work but after pushing to modulus it fails with an error whenever google crawls the site:

```
spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' } 
stderr:
```

I'm using the latest version of meteor. Do you think it could be an issue with Modulus and not the package? Or is there additional configuration I need to do?

Thanks for the help!

**Comment by gadicc** [comment]
Mmm, we usually see this error when the script we're passing to phantomjs doesn't complete, and the process gets killed after timing out.  So I think the problem is in spiderable (don't worry, we'll look into it), but I'd like to confirm a few things first:

1) Can you confirm in a Javascript console (in the browser) if the value of Meteor.release is definitely the same locally and in production.  (Did the project use to use an older version of Meteor that was upgraded?  I've seen this error before when using an older version of spiderable with a newer version of Meteor). 

2) Can you put the following code somewhere and confirm the output?

``` js
child_process.exec('phantomjs --version', 
  function(err, stdout, stderr) {
    console.log("PhantomJS version is " + stdout);
  }
);
```

3) Also just wanted to double check how you are testing locally?  Are you navigating to [http://localhost:3000/?_escaped_fragment_=](http://localhost:3000/?_escaped_fragment_=) and seeing the full page HTML and no errors from the Meteor process?

Gadi

**Comment by Lepozepo** [comment]
All right, Meteor.release is latest on development and production: "0.6.6.2". I added the snippet and I get "1.9.1" on production (modulus) and "1.9.2" on development. I'm testing by doing a curl command with the escaped fragment url. I do see the full html being rendered with no errors locally. When I do the same curl command on the server, I see the phantomjs failed error. I have no clue what it could be, lol.

**Comment by gadicc** [comment]
Ok no stress, that's all good :>  Just wanted to rule some stuff out initially.  So as best I can tell, there is no problem with meteor-phantomjs or Modulus, but we'll still figure this out.  Are you able to provide the production URL for me to do some tests?  If not, I'll send some details of what I have in mind.

**Comment by Lepozepo** [comment]
Sure: www.retrosoda.com is my production URL. We sell kick ass soda, lol. Thanks for the help ^_^

**Comment by gadicc** [comment]
Site's looking good!  Nice work :)

Yeah, as expected, phantomjs is getting stuck rendering the page, which is why it's being killed after timing out and you're getting that error.

phantomjs itself unfortunately just gives a very unhelpful `SyntaxError: Parse error`, without telling us which script is causing the problem.  I had a look in Chrome dev tools (phantomjs is also webkit based), and the only error I saw loading the page is this:

`Sorry, couldn't find a yield named "nav". Did you define it in one of the rendered templates like this: {{yield "nav"}}?`

That might be enough to through phantomjs, I'm not sure.  Can you try fix that and see if it makes a difference?

**Comment by Lepozepo** [comment]
Yeah, I don't know why that happens, it's weird. I'll try to get that fixed and see if that helps the issue. Thanks for the kudos ^_^.

**Comment by gadicc** [comment]
It's weirder that it works fine in development and not in production.  The minification seems to be changing something about the error (or maybe something else entirely - could be a bug), although it still seems fine on Chrome.

As for the error itself, check your Router.map calls for any mention of a "nav" yield.  Let me know what happens :>

**Comment by Lepozepo** [comment]
All right, all done, I removed the error and tested again. Same error :/. You think demeteorizer might be screwing it up somehow?

**Comment by gadicc** [comment]
I think more likely the minification process (via uglify), although it's still weird that there are no crashing errors in chrome.  I would have said it's a bug in phantomjs if it wasn't working fine in development mode.  It would be create to deploy in development mode, but I don't think this is possible with demeteorizer (although you could test locally with `mrt bundle` if you're up for it).  Beyond that, unfortunately I'm out of ideas... suggest you post on meteor-talk or stack overflow, you can reference this issue.

Here's the plain phantomjs script to test from outside of Meteor, with some console.logs I put in which indicates that Meteor is never getting fully loaded and the error is occuring very early on before Meteor.status is ever defined:

``` js
var url = 'http://www.retrosoda.com/';
var page = require('webpage').create();
page.open(url);
console.log('postopen');
setInterval(function() {
  var ready = page.evaluate(function () {
if (typeof Meteor !== 'undefined' && typeof(Meteor.status) !== 'undefined')
return 1;
    if (typeof Meteor !== 'undefined' && typeof(Meteor.status)
        !== 'undefined' && Meteor.status().connected) {
      Deps.flush();
      return DDP._allSubscriptionsReady();
    }
    return false;
  });
console.log(ready);
  if (ready) {
    var out = page.content;
    out = out.replace(/<script[^>]+>(.|\n|\r)*?<\/script\s*>/ig, '');
    out = out.replace('<meta name="fragment" content="!">', '');
    console.log(out);
    phantom.exit();
  }
}, 100);
```

Just to be clear, the problem is with phantomjs evaluating the deployed code, just not sure where/why :>

**Comment by Lepozepo** [comment]
Cool, thank you, I'll see what I can figure out ^_^

**Comment by amyzhaoyu** [comment]
I think I'm running into a similar issue - were you able to resolve the issue with phantomjs evaluating the deployed code?

**Comment by Lepozepo** [comment]
Nope, but I deployed in pogoapp and it seems to work there, lol

**Comment by gadicc** [comment]
Amyz, how similar an issue?  Are you working fine in development and experiencing this problem when deploying to Modulus?  Can you paste me the output of some of the debugging steps I mentioned above?  Do any of the testing/troubleshooting steps from http://www.meteorpedia.com/read/spiderable help you?

**Comment by payner35** [comment]
same problem here... works in local.. not in production...

**Comment by amyzhaoyu** [comment]
Ah sorry - I'm not deploying on Modulus ... I'm deploying my bundled app on my own server using nginx as a reverse proxy - I see the full page html on `localhost:3000?_escaped_fragment_=`, as well as on my production server if I deploy using Meteor, but I get the following issue in my log when I try using the `?_escaped_fragment_=` with the bundled app: 

```
spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }
```

**Comment by gadicc** [comment]
amyz/payner, is your production deploy public, so I can check some things?

(Or can you run the troubleshooting code from the Meteorpedia page, above, and check for errors?  Assuming that on the production site, there are no Javascript errors in your browser console).

**Comment by payner35** [comment]
hi..

https://eventsonic-11281.onmodulus.net/?_escaped_fragment_=

logs
http://screencast.com/t/pNI7SuJr7k

**Comment by gadicc** [comment]
Gavin, found this:

```
ReferenceError: Can't find variable: jQuery

  https://eventsonic-11281.onmodulus.net/js/jquery.backstretch.js:377
```

You'll have to investigate.  Strange that Chrome doesn't have this error but PhantomJS does.  Could be any number of things (probably load order or minification) that PhantomJS is more sensitive to.  You'll have to look into it.  You can keep using the script from Meteorpedia to find these kinds of errors.

**Comment by gadicc** [comment]
Oh I see you have that script included manually in your HEAD.  Don't do that :>  Especially when it's relying on a script (jQuery) that's being served minified.  Rather than manually loading the script, just dump it in your `client/compatibility` directory?

**Comment by amyzhaoyu** [comment]
Actually, when I go to `curl http://localhost:3000?_escaped_fragment_=`, even though I get the full body html, it also outputs these errors below before returning the page content:

```
TypeError: 'undefined' is not a function (evaluating 'this._emitWithSeverity.bind(this, i)')
TypeError: 'undefined' is not an object (evaluating 'Package['observatory-apollo'].Observatory')
```

Maybe it's related to this open issue: https://github.com/jhoxray/observatory/issues/30

**Comment by payner35** [comment]
was not aware of client/compatibility directory ;)  i have moved my extra js files to this now..

I'm now getting:  SyntaxError: Parse error

i have also bundled the code and run locally...   (without --debug to keep the code minified..) Everything works as it should..  http://screencast.com/t/nBklT6qrjZb

i have also read about some bug in Phantomjs. And that turing off Gzip help..  have tried with this.

connectHandler = WebApp.connectHandlers
connectHandler.use (req, res, next)->
    # res.setHeader(name, value);
        res.setHeader "accept-encoding", "gzip;q=0,deflate;q=0"
    next()

**Comment by gadicc** [comment]
@amyzhaoyu, without observatory, does phantomjs work?  Let's try hone in on source of the problem.

@payner35, and any luck without gzip?  I've never had to resort to that.  But unfortunately it is a sometimes cumbersome process of continually runnning the script to find errors.  The good news though is that even though PhantomJS is quite sensitive, weeding out these errors are definitely something you want to do in any event for all your users.  Stab in the dark, but what about the <script> you still have in your <head>?  (to reload document if css isn't ready)

**Comment by amyzhaoyu** [comment]
yes - the phantomjs errors go away once I remove observatory, so it seems that issue has something to do with spiderable and using nginx as a reverse proxy ... 

update: actually - getting rid of observatory solved the issue for me :) thanks so much for the help!

**Comment by payner35** [comment]
Managed to use https://github.com/mishoo/UglifyJS2 to debug the minified JS...  and catch my parse error as part of the "Select2" package i use.

uglifyjs myMinJs.js --source-map output.js.map

Parse error at ug.js:16,4118
Unexpected character '¼'

found some more info here.. 
https://github.com/mishoo/UglifyJS2/issues/328

not sure what to do now for a fix... but i have removed select2 and all works as it should with phantomjs

**Comment by Lepozepo** [comment]
@payner35 removing select2 has fixed this issue for me too. I tried solving it by doing this: http://stackoverflow.com/questions/11501289/uglify-js-error-unexpected-character-when-concatenating-then-minifying-selec but got nothing

**Comment by gadicc** [comment]
Sorry, friends, fell a bit behind here :>

@amyzhaoyu, glad you got it working!  yeah, that doesn't have much to do with using nginx as a reverse proxy, that should work absolutely fine unless it's setup weirdly.  very happy you referenced the issue on the oberservatory repo.

@payner35, great catch!!  Appreciate you taking the time to debug this and report back, as you can see, it's already helped others (@lepozepo) !  Likewise, if something in select2 (are you using it as a smart package?  dropped in compatibility folder?  <script> inclusion?), might be worth opening an issue in the appropriate place.

**Comment by payner35** [comment]
tried with both.. MRT package and using the js files in compatibility folder..  still the same error.

**Comment by gadicc** [comment]
@payner35, @Lepozepo, and other select2 users - I spent some more time looking into this.

problem is with the DIACRATICS line in select2.js (101), as described here:
https://github.com/mishoo/UglifyJS2/issues/328
Big props to github user payner35 for figuring out the connection.

Easiest fix, comment out the line (you'll lose diacratic support).

Best fix (not possible yet): get Meteor to pass { quote_keys: true } as an option to uglify.
The idea to pass options to uglify is discussed in this rather painful [thread](https://groups.google.com/d/msg/meteor-core/_7bZESTe-_I/gBe-ao6CNksJ).

Actually, I guess what we really need is to specify uglify options per package, since it's a shame to unnecessarily quote all keys.  Or maybe uglify should auto quote keys that cause problems on some browsers (old IE and PhantomJS), or maybe PhantomJS should not break on such unquoted keys :>

Above was mentioned in [meteor-talk](https://groups.google.com/d/msg/meteor-talk/7ZbidddRGo4/MpO09W_n8ZEJ).  Thanks again payner35 for tracing down the problem.

**Comment by dfischer** [comment]
+1 urlify breaking spiderable.

**Comment by nate-strauser** [comment]
i removed diacratics support from the select2 package - thanks for the effort in figuring out the root cause, saved me a bunch of time

**Comment by joshua1** [comment]
I started getting this error DIACRITICS is not defined with 3.4.8 . see line 117 in select2.js .
didn't have this error with the older version

**Comment by nate-strauser** [comment]
sorry about that - try 3.4.9

**Comment by joshua1** [comment]
thanks @nate-strauser , its all good now with 3.4.9
